name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID_DEV: landing-dev-cf5b5
  PROJECT_ID_PROD: landing-aabbb
  SERVICE_NAME: site-worker
  REGION: us-central1

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for GCP OIDC auth
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Assuming a JSON service account key is stored in GitHub Secrets
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ env.PROJECT_ID_DEV }}
          service: "site-jobs-processor" # Cloud Run service name
          region: "us-central1" # Cloud Run region
          source: "." # Build from source (uses Dockerfile)
          env_vars: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            SERPAPI_KEY=${{ secrets.SERPAPI_KEY }}
